FROM python:3.10.16-slim

ENV HOME="/usr/src/app"
ENV USD_BUILD_PATH="${HOME}/usd"

WORKDIR ${HOME}

# Required for compiling the USD source
RUN apt update && \
    apt install -y git \
	build-essential \
	cmake \
	nasm \
	libglew-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev zlib1g-dev libxt-dev


RUN git clone https://github.com/PixarAnimationStudios/USD usdsrc && \
    python usdsrc/build_scripts/build_usd.py ${USD_BUILD_PATH} --no-usdview && \
	# remove build files we no longer need to save space
	rm -rf usdsrc && \
	rm -rf ${USD_BUILD_PATH}/build && \
	rm -rf ${USD_BUILD_PATH}/cmake && \
	rm -rf ${USD_BUILD_PATH}/pxrConfig.cmake && \
	rm -rf ${USD_BUILD_PATH}/share && \
	rm -rf ${USD_BUILD_PATH}/src





RUN apt-get purge -y git \
	build-essential \
	cmake \
	nasm \
	libglew-dev \
	libxrandr-dev \
	libxinerama-dev \
	libxi-dev \
	zlib1g-dev && \
	apt autoremove -y && \
	apt-get autoclean -y

